sales_data_modeling_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var ('PGHOST') }}"
      user: "{{ env_var ('PGUSER') }}"
      password: "{{ env_var ('PGPASSWORD') }}"
      port: "{{ env_var ('PGPORT') | int }}"
      dbname: "{{ env_var ('PGDATABASE') }}"
      schema: "{{ env_var ('DBT_SCHEMA') }}"
      threads: 4