# COMMON SETTINGS FOR APPs SERVICES
x-app-common: &app-common
  env_file:
    - .env
  environment:
    PGUSER: ${PGUSER}
    PGPASSWORD: ${PGPASSWORD}
    PGPORT: ${PGPORT}
    PGDATABASE: ${PGDATABASE}
    PGHOST: ${PGHOST}
  networks:
    - spark-network


services:
  project-db:
    <<: *app-common
    image: postgres:15
    container_name: sales-data-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 20s
      retries: 5
    volumes:
      - sales-data-db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/set_password.sh:/docker-entrypoint-initdb.d/set_password.sh

volumes:
  sales-data-db:
    driver: local

networks:
  spark-network:
    external: true
    #driver: bridge