# DBT CORE IMAGE BUILD
x-dbt-core-build-config: &dbt-build-config
  context: .
  dockerfile: dockerfiles/dbt_docker/dbt.Dockerfile


services:

  dbt_core_local:
    image: dbt_core_local
    build: *dbt-build-config

  dbt:
    image: dbt_core_local
    container_name: local-dbt-core
    working_dir: /usr/app/dbt/sales_data_modeling_dbt
    env_file:
      - .env
    command:
      - dbt --version
      - dbt --profiles-dir /usr/app/dbt debug
    volumes:
      - ./dbt:/usr/app/dbt
    networks:
      - spark-network


networks:
  spark-network:
    external: true