version: 2

models:
  - name: stg_drivers
    description: "dbt model for 'drivers' table"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null